
server:
  port: 9527


#实例名
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true



#使用zuul添加路由映射规则   这个服务对应的路径  使用mydept 这个前缀
zuul:
  routes:
     mydept.serviceId: microservicecloud-dept
     mydept.path: /mydept/**
  ignored-services: microservicecloud-dept #服务单入单出将无法再通过  http://myzuul.com:9527/microservicecloud-dept/* 访问


info:
  app.name: hhf-microcloud
  company.name: www.hhf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


